kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: shlomo2096-dev
  uid: 0e0fb69d-c6f4-4590-9b27-3bf0ce1487bd
  resourceVersion: '2608959107'
  creationTimestamp: '2025-08-17T12:59:28Z'
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
spec:
  clusterIP: 172.30.39.232
  ipFamilies:
    - IPv4
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.39.232
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: mysql
status:
  loadBalancer: {}
